### ISSUE TITLE
老哥优秀啊，有时间一起开发个LOL自动走A的呗

### ISSUE THREAD

**Issue by gflkdns** [bode135/YellowCard#5]
我最近写了个LOL自动走A脚本 ， 没办法想玩天使，走A难受，结果一运行发现LOL按键没反应。。

https://github.com/miqt/PythonLearn/blob/master/ZiDongZouA.py 在外面运行没问题，进游戏就被屏蔽了

有时间一起搞事啊 ψ(*｀ー´)ψ

**Comment by Taeyeonzpx** [comment]
> 我最近写了个LOL自动走一个脚本，没办法想玩天使，走A难受，结果一运行发现LOL按键没反应。。
> 
> https://github.com/miqt/PythonLearn/blob/master/ZiDongZouA.py在室外运行没问题，进游戏就被发光了
> 
> 有时间一起搞事啊 ψ(*｀ー´)ψ(*｀ー´)ψ

后面你解决了吗? 进游戏失效的问题
